# 使用 .NET 8.0 SDK 作為構建階段
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# 複製 csproj 和 nuget.config 文件
COPY ["*.csproj",  "./"]

# 恢復依賴項
RUN dotnet restore

# 複製其他源代碼
COPY . .

# 構建應用程序
RUN dotnet publish -c Release -o out

# 使用 .NET 8.0 ASP.NET Core Runtime 作為運行階段
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "CustomerApi.dll"]

# 暴露應用程序監聽的端口
EXPOSE 8080
