services:
  customerapi:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:8080"

  nginx:
    image: nginx:latest
    ports:
      - "5050:3030"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - customerapi
